[global]
workers = 1

[development]
address = "0.0.0.0"
port = 6161
log = "normal"

[staging]
address = "0.0.0.0"
port = 6161
log = "normal"

[production]
address = "0.0.0.0"
port = 6161
log = "critical"
